language: python
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
    - pypy3.5
    - pypy3.6
env:
    - EIDER_WS_LIB=aiohttp
    - EIDER_WS_LIB=websockets
matrix:
    allow_failures:
        - python: 3.8-dev
install:
    - pip install .
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements-dev-py34.txt; else pip install -r requirements-dev.txt; fi
script:
    - pytest
    - flake8
