language: python
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7-dev
install:
    - pip install .
    - pip install -r requirements-dev.txt
script:
    - EIDER_WS_LIB=aiohttp py.test
    - EIDER_WS_LIB=websockets py.test
    - flake8
